=== AbhinavM2000/faculty/data/schema.json
{
	"$schema": "http://json-schema.org/draft-03/schema#",
	"title": "Amy's faculty website data schema",
	"type": "object",
	"properties": {
		"sources": {
			"type": "object",
			"description": "Conference and journal sources.",
			"required": true,
			"additionalProperties": {
				"type": "object",
				"description": "Source names",
				"required": true,
				"properties": {
					"name": {
						"type": "string",
						"requried": true
					},
					"short": {
						"type": "string",
						"requried": true
					}
				}
			}
		},
	    "pubs": {
			"type": "array",
			"description": "List of publications.",
			"required": true,
			"items": {
				"type": "object",
				"description": "A publication.",
				"properties": {
					"id": {
						"type": "string",
						"required": true
					},
					"kind": {
						"type": "string",
						"required": true,
						"enum": ["refereed conference paper", "refereed workshop paper", "journal article", "refereed short conference paper", "juried conference paper", "book chapter", "refereed invited article", "non-refereed workshop paper", "technical report", "refereed magazine article", "whitepaper", "abstract"]
					},
					"authors": {
						"type": "array",
						"required": true,
						"items": {
							"type": "string"
						}
					},
					"deadname": {
						"type": "boolean",
						"required": true
					},
					"year": {
						"type": "integer",
						"required": true
					},
					"title": {
						"type": "string",
						"required": true
					},
					"source": {
						"type": "string",
						"required": true
					},
					"pages": {
						"type": ["string", "null"],
						"required": true
					},
					"doi": {
						"type": ["string", "null"],
						"required": false
					},
					"local": {
						"type": ["string", "null"],
						"required": true
					},
					"authorizer": {
						"type": ["string", "null"]
					},
					"publisher": {
						"type": "string",
						"required": true
					},
					"contribution": {
						"type": "string",
						"required": true
					}
				}
			}
	    },
	    "people": {
			"type": "array",
			"description": "List of people.",
			"required": true,
			"items": {
				"type": "object",
				"description": "A person.",
				"properties": {
					"id": {
						"type": "string",
						"required": true
					},
					"name": {
						"type": "string",
						"required": true
					},
					"active": {
						"type": "boolean",
						"required": true
					},
					"advised": {
						"type": "boolean",
						"required": true
					},
					"level": {
						"type": "string",
						"required": true,
						"enum": ["undergrad", "phd", "postdoc", "director"]
					},
					"dept": {
						"type": "string",
						"required": true
					},
					"coadvisor": {
						"type": ["string", "null"],
						"required": true
					},
					"bio": {
						"type": "string",
						"required": true
					},
					"url": {
						"type": "string",
						"required": true
					},
					"startdate": {
						"type": "integer",
						"required": true
					},
					"enddate": {
						"type": ["integer", "null"],
						"required": true
					},
					"achievements": {
						"type": "array",
						"required": true,
						"items": {
							"type": "string"							
						}
					}
				}
			}
	    },
	    "projects": {
			"type": "array",
			"description": "List of projects.",
			"required": true,
			"items": {
				"type": "object",
				"description": "A person.",
				"properties": {
					"id": {
						"type": "string",
						"required": true
					},
					"active": {
						"type": "boolean",
						"required": true
					},
					"name": {
						"type": "string",
						"required": true
					},
					"description": {
						"type": "string",
						"required": true
					},
					"funding": {
						"type": "array",
						"required": true,
						"items": {
							"type": "string"
						}
					},
					"people": {
						"type": "array",
						"required": true,
						"items": {
							"type": "string"
						}
					},
					"papers": {
						"type": "array",
						"required": true,
						"items": {
							"type": "string"
						}
					},
					"links": {
						"type": "array",
						"required": true,
						"items": {
							"type": "object",
							"required": true,
							"properties": {
								"title": {
									"type": "string",
									"required": true
								},
								"url": {
									"type": "string",
									"required": true
								}
							}
						}
					},
					"startdate": {
						"type": "integer",
						"required": true
					},
					"stopdate": {
						"type": ["integer", "null"],
						"required": true
					},
					"impact": {
						"type": "string",
						"required": true
					}
				}
			}
	    },
	    "posts": {
			"type": "array",
			"description": "List of posts.",
			"required": true,
			"items": {
				"type": "object",
				"description": "A blog post.",
				"required": true,
				"properties": {
					"url": {
						"type": "string",
						"required": true
					},
					"title": {
						"type": "string",
						"required": true
					},
					"date": {
						"type": "string",
						"required": true
					},
					"tags": {
						"type": "array",
						"required": true,
						"items": {
							"type": "string"
						}
					},
					"img": {
						"type": ["string", "null"],
						"required": true
					},
					"alt": {
					    "type": ["string", "null"],
					    "required": true
				    }
				}
			}
	    },
	    "impacts": {
			"type": "array",
			"description": "List of impacts.",
			"required": true,
			"items": {
		    	"type": "object",
				"description": "A population impacted.",
		    	"properties": {
			    	"id": {
				    	"type": "string",
				    	"required": true
			    	},
			    	"population": {
				    	"type": "string",
				    	"required": true
			    	},
			    	"alt": {
				    	"type": "string",
				    	"required": true
			    	},
			    	"description": {
				    	"type": "string",
				    	"required": true
			    	},
			    	"impacts": {
				    	"type": "array",
				    	"required": true,
				    	"items": {
					    	"type": "string"
				    	}
			    	}
		    	}
			}
	    },
	    "cv": {
			"type": "object",
			"description": "CV data structures.",
			"required": true
	    },
	    "travel": {
			"type": "array",
			"description": "List of trips.",
			"required": true,
			"items": {
				"type": "object",
				"required": true,
				"description": "A trip.",
				"properties": {
					"url": {
						"type": ["string", "null"],
						"required": true
					},
					"title": {
						"type": "string",
						"required": true
					},
					"details": {
						"type": "string",
						"required": true
					},
					"date": {
						"type": "string",
						"required": true
					},
					"report": {
						"type": ["string", "null"],
						"required": true
					}
				}
			}
	    },
	    "talks": {
			"type": "array",
			"description": "List of talks.",
			"required": true,
			"items": {
				"type": "object",
				"description": "A talk.",
				"properties": {
					"date": {
						"type": "string",
						"required": true
					},
					"image": {
						"type": "string",
						"required": true
					},
					"alt": {
						"type": "string",
						"required": true
					},
					"slides": {
						"type": "string",
						"required": true
					},
					"venue": {
						"type": "string",
						"required": true
					},
					"url": {
						"type": ["string", "null"],
						"required": true
					},
					"recording": {
						"type": ["string", "null"],
						"required": true
					},
					"practice": {
						"type": ["string", "null"],
						"required": true
					},
					"description": {
						"type": "string",
						"required": true
					},
					"keynote": {
						"type": "boolean",
						"required": true
					}
				}
			}
		},
		"classes": {
			"type": "array",
			"description": "List of classes.",
			"required": true,
			"items": {
				"type": "object",
				"description": "A class.",
				"properties": {
					"id": {
						"type": "string",
						"required": true
					},
					"alt": {
						"type": "string",
						"required": true
					},
					"link": {
						"type": "string",
						"required": true
					},
					"date": {
						"type": "string",
						"required": true
					},
					"title": {
						"type": "string",
						"required": true
					},
					"description": {
						"type": ["string", "null"],
						"required": true
					},
					"links": {
						"type": "array",
						"description": "List of posts.",
						"required": true,
						"items": {
							"type": "object",
							"required": true,
							"description": "A trip.",
							"properties": {
								"description": {
									"type": "string",
									"required": true
								},
								"link": {
									"type": "string",
									"required": true
								}
							}
						}
					}
				}
			}
		},
		"books": {
			"type": "array",
			"description": "List of books.",
			"required": true,
			"items": {
				"type": "object",
				"description": "A class.",
				"properties": {
					"image": {
						"type": "string",
						"required": true
					},
					"alt": {
						"type": "string",
						"required": true
					},
					"link": {
						"type": "string",
						"required": true
					},
					"title": {
						"type": "string",
						"required": true
					},
					"description": {
						"type": "string",
						"required": true
					},
					"editor": {
						"type": "boolean",
						"required": true
					}
				}
			}
		},
		"years": {
			"type": "object",
			"description": "Metadata about years."
		},
		"commitments": {
			"type": "array",
			"description": "A list of commitments",
			"required": true,
			"items": {
				"type": "array",
				"description": "Fields for a commitment",
				"requried": true,
				"items": [
					{
						"type": "string",
						"required": true
					},
					{
						"type": "string",
						"required": true
					},
					{
						"type": "string",
						"required": true,
						"enum": ["research", "service", "teaching", "personal"]
					},
					{
						"type": "string",
						"required": true,
						"enum": ["flexible", "required", "prime"]
					},
					{
						"type": "int",
						"required": true,
						"minimum": 1
					},
					{
						"type": "string",
						"required": true,
						"enum": ["weekly", "annually"]
					},
					{
						"type": ["int", "string"],
						"required": false
					},
					{
						"type": ["int", "string"],
						"required": false
					}
				]
			}
		}
	}
}

=== AbhinavM2000/faculty/data/data.json
{
	"people": [
		{
	 		"id": "perdriau",
	 		"name": "ChrisÂ  Perdriau",
	 		"active": true,
	 		"advised": true,
	 		"level": "undergrad",
	 		"dept": "Oregon State University",
	 		"coadvisor": null,
	 		"bio": "Chris is a CS student at Oregon State University studying HCI and psychology. He is interested in making technology more inclusive for underserved communities.",
	 		"url": "https://github.com/ChristopherPerdriau",
	 		"startdate": 2020,
	 		"enddate": null,
	 		"achievements": []
	 	},
		{
	 		"id": "anael",
	 		"name": "Anael Kuperwajs Cohen",
	 		"active": true,
	 		"advised": true,
	 		"level": "undergrad",
	 		"dept": "Macalester College",
	 		"coadvisor": null,
	 		"bio": "Anael is a CS and applied mathematics and statistics double major with a cognitive science concentration at Macalester College. She is interested in breaking down barriers for women and other minorities within the field of CS by pursuing a career in CS education.",
	 		"url": "https://anaelkuperwajs.github.io/",
	 		"startdate": 2020,
	 		"enddate": null,
	 		"achievements": []
	 	},
		{
	 		"id": "minatari",
	 		"name": "Mina Tari",
	 		"active": true,
	 		"advised": false,
	 		"level": "phd",
	 		"dept": "The Information School",
	 		"coadvisor": null,
	 		"bio": "Mina is PhD student in the Information School exploring women of color's experiences in introductory computing courses. She's a homegrown UW student, coming from the Informatics and Gender, Women, and Sexuality Studies programs. Mina works with Amy and the lab to apply a critical feminist lens to questions regarding equity in computing education.",
	 		"url": "http://minatari.com/",
	 		"startdate": 2018,
	 		"enddate": null,
	 		"achievements": []
	 	},
		{
	 		"id": "jliang9",
	 		"name": "Jenny Liang",
	 		"active": true,
	 		"advised": true,
	 		"level": "undergrad",
	 		"dept": "Computer Science & The Information School",
	 		"coadvisor": null,
	 		"bio": "Jenny is an undergrad studying computer science and informatics. She is working with Amy to study how to use explicit programming strategies to improve collaboration and learning of developers.",
	 		"url": "https://www.linkedin.com/in/jenny-liang/",
	 		"startdate": 2020,
	 		"enddate": null,
	 		"achievements": []
	 	},
		{
	 		"id": "eboris",
	 		"name": "Emilia Borisova",
	 		"active": true,
	 		"advised": true,
	 		"level": "undergrad",
	 		"dept": "Pre-major",
	 		"coadvisor": null,
	 		"bio": "Emilia is an undergraduate student pursuing Informatics. She is interested in computing education and is helping with Neil's research on understanding the personal and interpersonal factors influencing computing career choices. ",
	 		"url": "https://www.linkedin.com/in/emilia-borisova",
	 		"startdate": 2020,
	 		"enddate": null,
	 		"achievements": []
	 	},
		{
	 		"id": "st3f",
	 		"name": "Stefania Druga",
	 		"active": true,
	 		"advised": true,
	 		"level": "phd",
	 		"dept": "Information School",
	 		"coadvisor": null,
	 		"bio": "Stefania Druga is the creator of http://cognimates.me, a platform for AI education for kids, which started as her Master Thesis at MIT Media Lab. Currently is a Ph.D. student at the University of Washington. She has observed in longitudinal studies how 450 children from 7 countries are growing up with AI and how hey can acquire AI literacy concepts through creative learning activities. She is co-advised by Benjamin Mako Hill.",
	 		"url": "http://www.drugastefania.com",
	 		"startdate": 2019,
	 		"enddate": null,
	 		"achievements": []
	 	},
		{
			"id": "chandrashree",
			"name": "Chandrashree Karnani",
			"active": false,
			"advised": true,
			"level": "undergrad",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "Chandrashree is studying data science in the Informatics program. She's interested in how data can be used to make informed decisions. She's helping with Yim's work on machine learning literacy.",
			"url": "http://www.linkedin.com/in/chandrashree-karnani-4824b0178",
			"startdate": 2019,
			"enddate": 2019,
			"achievements": []
		},
		{
			"id": "zcolah",
			"name": "Zoshua Colah",
			"active": false,
			"advised": true,
			"level": "undergrad",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "Zoshua is an Informatics major specializing in UX Design and Data Science who spends his time helping freshman and sophomore students learn more about tech.",
			"url": "https://zcolah.myportfolio.com/",
			"startdate": 2019,
			"enddate": 2019,
			"achievements": []
		},
		{
			"id": "neilryan",
			"name": "Neil Ryan",
			"active": true,
			"advised": true,
			"level": "phd",
			"dept": "Computer Science",
			"coadvisor": null,
			"bio": "Neil is a PhD student in Computer Science and Engineering, curiously pursuing connections between debugging, self-regulation, meta-cognition, tacit knowledge, and programming strategies.",
			"url": "https://neildryan.com/",
			"startdate": 2018,
			"enddate": null,
			"achievements": []
		},
		{
			"id": "chriszh",
			"name": "Christina Zhang",
			"active": false,
			"advised": true,
			"level": "undergrad",
			"dept": "Computer Science and the Information School",
			"coadvisor": null,
			"bio": "Christina is an undergraduate majoring in Computer Science and Informatics. She's working on supporting research on intelligent programmin tutors.",
			"url": "https://www.linkedin.com/in/christina9/",
			"startdate": 2019,
			"enddate": 2019,
			"achievements": []
		},
		{
			"id": "mattjd",
			"name": "Matt Davidson",
			"active": true,
			"advised": false,
			"level": "phd",
			"dept": "College of Education",
			"coadvisor": null,
			"bio": "Matt is a doctoral in measurement & statistics who has collaborated closely on the lab's work on assessments of programming skills.",
			"url": "https://www.linkedin.com/in/matt-davidson-92379916/",
			"startdate": 2017,
			"enddate": null,
			"achievements": []
		},
		{
			"id": "meron",
			"name": "Meron Solomon",
			"active": true,
			"advised": true,
			"level": "undergrad",
			"dept": "pre-major",
			"coadvisor": null,
			"bio": "Meron is an undergraduate who helped design and teach an innovative new computing course to Upward Bound students in 2019.",
			"url": "https://www.linkedin.com/in/meron-solomon-aa81a5169/",
			"startdate": 2019,
			"enddate": null,
			"achievements": []
		},
		{
			"id": "patold",
			"name": "Patrick Old",
			"active": false,
			"advised": true,
			"level": "undergrad",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "Patrick was an undergraduate studying Informatics and Oceanography. He worked on a project to observe his growth as a teacher via participant observation.",
			"url": "https://www.linkedin.com/in/pat-old/",
			"startdate": 2018,
			"enddate": 2019,
			"achievements": []
		},
		{
			"id": "andrewhu",
			"name": "Andrew Hu",
			"active": true,
			"advised": true,
			"level": "undergrad",
			"dept": "Computer Science and Education",
			"coadvisor": null,
			"bio": "Andrew is a CS & Education double major interested in pedagogical techniques and student motivation in CS Ed.",
			"url": "http://students.washington.edu/andrewhu",
			"startdate": 2018,
			"enddate": null,
			"achievements": []
		},
		{
			"id": "olesona",
			"name": "Alannah Oleson",
			"active": true,
			"advised": true,
			"level": "phd",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "Alannah is a PhD student in the Information School, broadly interested in the learning and teaching of inclusive software design methods. Before joining UW, she studied gender-inclusive software at Oregon State University.",
			"url": "https://alannaholeson.com/",
			"startdate": 2018,
			"enddate": null,
			"achievements": [ "NSF Graduate Research Fellowship (2018)" ]
		},
		{
			"id": "yreg",
			"name": "Yim Register",
			"active": true,
			"advised": false,
			"level": "phd",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "Yim is a PhD student in the Information School, broadly interested in machine learning literacy. Before joining UW, they studied cognitive science at the University of Rochester.",
			"url": "http://students.washington.edu/yreg/",
			"startdate": 2018,
			"enddate": null,
			"achievements": [ "NSF Graduate Research Fellowship (2019)" ]
		},
		{
			"id": "janeq97",
			"name": "Jane Quichocho",
			"active": false,
			"advised": true,
			"level": "undergrad",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "Jane helped the lab on various learning to code projects.",
			"url": "https://www.linkedin.com/in/jane-quichocho-08a9b714b/",
			"startdate": 2018,
			"enddate": 2019,
			"achievements": []
		},
		{
			"id": "wkwok16",
			"name": "William Kwok",
			"active": false,
			"advised": true,
			"level": "undergrad",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "William is an undergraduate in the Information School. He supported the lab's research on programming tutors by advancing design, development, instruction, and ideation relation to expressing agency when learning computing online.",
			"url": "http://williamk.info/?q=cc",
			"startdate": 2018,
			"enddate": 2019,
			"achievements": []
		},
		{
			"id": "akkarh",
			"name": "Harshitha Akkaraju",
			"active": false,
			"advised": true,
			"level": "undergrad",
			"dept": "Information School",
			"coadvisor": null,
			"bio": "Harshitha is an undergraduate in the Information School. She supported the lab's research on programming tutors by advancing design, development, instruction, and ideation relation to expressing agency when learning computing online.",
			"url": "https://harshitha-akkaraju.github.io/",
			"startdate": 2018,
			"enddate": 2019,
			"achievements": []
		},
		{
			"id": "laurav4",
			"name": "Laura Vonessen",
			"active": false,
			"advised": false,
			"level": "phd",
			"dept": "Computer Science",
			"coadvisor": "Katharina Reinecke",
